#!/bin/bash
#Kekai Tanaka
#10/16/2014
./is-quant.sh $2
exit=$?
if [ $# -ne 2 ]
then
 echo "use two command line arguments"
 exit 9
elif [ $exit -eq 0 ]
then
for (( i=1; i<=$2; i++ ))
do
  echo -n "$1"
done
echo
elif [ $exit -ne 0 ]
then
 echo "needs to be non negative integer"
 exit 1
 fi
